name = "qwenapi"                # todo
main = "index.js"
compatibility_date = "2024-06-06"

[ai]
binding = "AI" # i.e. available in your Worker on env.AI

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "openai-cf-images"
preview_bucket_name = "ai-images"

[vars]
CLOUDFLARE_ACCOUNT_ID = "f52fafdade5f6818f12471a430a13e6d" # replace with your own.
MODEL_MAPPER = { "gpt-3.5-turbo" = "@cf/qwen/qwen1.5-14b-chat-awq" } # Optional
